#x^2 - d(y^2 + z^2) = 1
#HSC (hyperbolic curve operation)
    #check (check p is on the hsc or not) 
    #findcoord (find the coordinates of giving x on the curve)
    #recordNcoord (print all N coordinates)
    #drawNcoord (draw all N coordinates)
    #add (modadd)                                   --in process 
    #mul (montgomary ladder)                        --in process 
    #recordncoord (record all n coordinates)        --in process 
    #drawncoord (draw all n coordinates)            --in process 
#example
from Crypto.Util.number import isPrime
from sympy.ntheory.residue_ntheory import sqrt_mod
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from mpl_toolkits.mplot3d import Axes3D

class HSC_Discrete_Image: 
    def __init__(self, d, p):
        self.zero = (1, 0, 0)
        self.d = d
        self.p = p
        #to check d is perfect square or not if yes curve will degrade
        if pow(d, (p - 1) // 2, p) == 1 or not isPrime(p):
            raise ValueError("The Curve has Defects")

        self.countN, self.containerN = self.recordNcoord()

    def check(self, p):
        if p == self.zero:
            return True

        x, y, z = p

        if not (0 <= x < self.p and 0 <= y < self.p and 0 <= z < self.p) or \
        not (x**2 - self.d * (y**2 + z**2) - 1) % self.p == 0:
            raise ValueError("Invalid point")

        #to check the point have root or not 
        #in order to make it work this line cant exist because every points must be able to be calculate
        if sqrt_mod((y**2 + z**2), self.p) == None:
            raise ValueError("Invalid point")

        return True

    #find the coordinates of given x
    def findcoord(self, x): 
        # to check x is out of range or not
        if x < self.p:
            #to transform the esc equation in order to make find r more clearer and easier
            #y^2 + z^2 = (x^2 - 1) / d
            r = (x**2 - 1) * pow(self.d, -1, self.p) % self.p

            container_findcoord = []

            #to brute force the r to check is there any r can match the given x that conform the esc equation 
            for y in range(self.p):
                z_sq = (r - y**2) % self.p
                z = sqrt_mod(z_sq, self.p) 
                if z != None:
                    container_findcoord.append((x, y, z))
                    if z != 0: 
                        container_findcoord.append((x, y, -z % self.p))
            if container_findcoord == []: 
                raise ValueError("Not found") 
            else: 
                return container_findcoord
        else:
            raise ValueError("Out of range")

    #find the total points that can appear on the esc that generated by the given variable
    def recordNcoord(self):
        #the 1 point means the point at infinity 
        containerN = {self.zero}
        
        #to brute force in order to find the total point 
        for x in range(self.p):
            try:
                #store the list of coord based on given x
                container_findcoord = self.findcoord(x)
                containerN.update(container_findcoord)
            except Exception:
                pass
        return len(containerN), containerN

    def drawNcoord(self):
        x_coords = [p[0] for p in self.containerN if p is not None]
        y_coords = [p[1] for p in self.containerN if p is not None]
        z_coords = [p[2] for p in self.containerN if p is not None]

        #create background
        fig = plt.figure(figsize=(8, 8))
        ax = fig.add_subplot(111, projection='3d')

        #draw the points
        sc = ax.scatter(x_coords, y_coords, z_coords, s=30, facecolors='none', edgecolors='#3498db', linewidth=1.5)
#x^2 - d(y^2 + z^2) = 1
        #set the title
        ax.set_title(fr"$x^2 {-self.d:+}(y^2 + z^2) = 1 \text{{ (mod {self.p})}}$", fontsize=15)

        #show coord
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.yaxis.set_major_locator(MaxNLocator(integer=True))
        ax.zaxis.set_major_locator(MaxNLocator(integer=True))

        #set the edge
        ax.set_xlim(0, self.p - 1)
        ax.set_ylim(0, self.p - 1)
        ax.set_zlim(0, self.p - 1)
    
#example
if __name__ == "__main__":
    #a, b = -7, 10
    #p = 19, 41
    d, p = -7, 41
    g = (1, 0, 0)
    hsc = HSC_Discrete_Image(d=d, p=p) 
    print("-------------------------------------------\n") 
    
    countN, containerN = hsc.countN, hsc.containerN
    print(f"HSC: x^2 - {d}y^2 mod({p}) = 1")
    print(f"Counts: {countN}, Container: {containerN}")
    hsc.drawNcoord()
    print("\n-------------------------------------------\n") 

    # countn, containern = hsc.recordncoord(g)
    # print(f"Generates Point: {g}")
    # print(f"Counts: {countn}, Container: {containern}")
    # print(f"h: {countN//countn}")
    # hsc.drawncoord(g)
    # print("\n-------------------------------------------") 
    plt.show()